"""Everything the analysis reads, from the gold marts and nothing else.

The heavy lifting -- one row per satellite per day, ten million of them -- is
done in DuckDB, and only compact tables reach Python: one row per satellite
per storm, and sums per generation, shell and month for the cross-check.

**The period is pinned** to 2020-01-01 .. 2026-09-16, the last day with
complete space weather when the analysis was first run. The warehouse grows
every night; a figure that silently changed with it could not be reproduced.

**Every satellite has a life in three phases**, derived here because the marts
flag thrust only when it raises an orbit quickly:

- *raising*: before it first reaches its home shell -- the 25 km altitude shell
  where it spent most of its analysis-ready days;
- *operational*: from then until it last left that shell. Station-keeping
  thrusters cancel drag here, so only a storm's excess over the satellite's own
  pre-storm baseline is a drag signal;
- *descending*: after it left for good. Used for the cross-check, and only in
  months when it actually lost at least a kilometre: a satellite that moved to
  another shell and kept station there is not decaying.

**Floating-point sums are rounded before they leave.** DuckDB adds in parallel,
so the last bits of a mean can differ between runs; rounding to far below any
physical resolution is what lets the figures be regenerated byte for byte.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path
from typing import Final

import duckdb
import polars as pl

PERIOD_START: Final = dt.date(2020, 1, 1)
PERIOD_END: Final = dt.date(2026, 9, 16)

BASELINE_DAYS: Final = (-6, -2)
"""Days from a storm's peak averaged as the satellite's own quiet baseline."""
RESPONSE_DAYS: Final = (0, 2)
"""Days from the peak averaged as its response: the thermosphere reacts within
hours and relaxes over one to two days."""
CURVE_DAYS: Final = (-6, 6)
Window = tuple[int, int]
MIN_BASELINE_DAYS: Final = 3
MIN_RESPONSE_DAYS: Final = 2
DESCENT_MIN_LOSS_KM: Final = 1.0
DESCENT_MIN_DAYS: Final = 10


def connect(database: Path) -> duckdb.DuckDBPyConnection:
    """A read-only connection with the phase tables built. Nothing is written."""
    con = duckdb.connect(str(database), read_only=True)
    con.execute("SET memory_limit = '3GB'; SET threads = 4; SET TimeZone = 'UTC'")
    con.execute(f"""
        create temp table ready as
        select norad_id, epoch_date, generation, altitude_shell_km, mean_altitude_km,
               altitude_rate_km_per_day * 1000.0 as rate_m, ap_mean, f10_7_sfu, dst_min_nt
        from main.fct_daily_decay
        where is_analysis_ready
          and epoch_date between date '{PERIOD_START}' and date '{PERIOD_END}'
    """)
    con.execute("""
        create temp table phases as
        with days_in_shell as (
            select norad_id, altitude_shell_km, count(*) as days from ready group by all
        ),
        home as (
            -- Most days wins; a tie goes to the lower shell, so the choice is
            -- deterministic.
            select norad_id,
                   arg_max(altitude_shell_km, days * 10000 - altitude_shell_km) as home_shell
            from days_in_shell group by norad_id
        )
        select ready.norad_id, home.home_shell,
               min(epoch_date) filter (where altitude_shell_km = home_shell) as operational_from,
               max(epoch_date) filter (where altitude_shell_km = home_shell) as operational_to
        from ready join home using (norad_id)
        group by all
    """)
    return con


def storms(
    con: duckdb.DuckDBPyConnection,
    baseline: Window = BASELINE_DAYS,
    response: Window = RESPONSE_DAYS,
) -> pl.DataFrame:
    """Every storm in the period, and why each excluded one was excluded.

    A storm is kept only if no storm day falls in its baseline window or the
    day before it -- for the default baseline, peak-7 .. peak-2. Otherwise the
    "quiet" baseline is a storm itself, or a previous storm's recovery. The day
    just before the peak is not checked: it can be the storm's own onset.
    """
    latest_peak = PERIOD_END - dt.timedelta(days=response[1])
    return con.execute(f"""
        with storm as (
            select distinct storm_id, peak_date, peak_dst_nt, peak_ap, f10_7_sfu
            from main.fct_storm_epoch
            where peak_date between date '{PERIOD_START}' and date '{PERIOD_END}'
        ),
        storm_days as (select epoch_date from main.fct_space_weather_daily where is_storm_day)
        select storm.*,
            case
                when peak_date > date '{latest_peak}' then 'response window after the period'
                when exists (
                    select 1 from storm_days
                    where epoch_date between storm.peak_date - {1 - baseline[0]}
                                         and storm.peak_date - {-baseline[1]}
                ) then 'storm days in the baseline window'
            end as excluded_because
        from storm order by peak_date
    """).pl()


def storm_responses(
    con: duckdb.DuckDBPyConnection,
    baseline: Window = BASELINE_DAYS,
    response: Window = RESPONSE_DAYS,
) -> pl.DataFrame:
    """One row per operational satellite per clean storm: baseline, response, and
    their difference in m/day. Negative is falling faster during the storm."""
    (b0, b1), (r0, r1) = baseline, response
    clean = storms(con, baseline, response).filter(pl.col("excluded_because").is_null())
    con.register("clean_storms", clean.to_arrow())
    frame = con.execute(f"""
        with windowed as (
            select s.storm_id, s.peak_dst_nt, s.f10_7_sfu, r.norad_id, r.generation, p.home_shell,
                   date_diff('day', s.peak_date, r.epoch_date) as day, r.rate_m
            from clean_storms s
            join ready r on r.epoch_date between s.peak_date + {b0} and s.peak_date + {r1}
            join phases p on p.norad_id = r.norad_id
                          and r.epoch_date between p.operational_from and p.operational_to
        )
        select storm_id, peak_dst_nt, f10_7_sfu, norad_id, generation, home_shell as shell_km,
               avg(rate_m) filter (where day between {b0} and {b1}) as baseline_m,
               avg(rate_m) filter (where day between {r0} and {r1}) as response_m,
               count(*) filter (where day between {b0} and {b1}) as baseline_days,
               count(*) filter (where day between {r0} and {r1}) as response_days
        from windowed group by all
        having baseline_days >= {MIN_BASELINE_DAYS} and response_days >= {MIN_RESPONSE_DAYS}
    """).pl()
    con.unregister("clean_storms")
    return _round(
        frame.with_columns((pl.col("response_m") - pl.col("baseline_m")).alias("delta_m"))
    ).sort(["storm_id", "norad_id"])


def epoch_curves(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    """Mean altitude rate relative to each satellite's own baseline, by day from
    peak, for the satellite-storms the model uses. What figure 2 draws."""
    responses = storm_responses(con).select("storm_id", "norad_id", "baseline_m")
    con.register("used", responses.to_arrow())
    # Expanded to the exact (satellite, date) pairs wanted, so the join is on
    # equality. Joining on the satellite and filtering by date range built
    # hundreds of millions of intermediate rows and ran out of memory.
    frame = con.execute(f"""
        with wanted as (
            select u.norad_id, u.baseline_m, p.home_shell,
                   unnest(range({CURVE_DAYS[0]}, {CURVE_DAYS[1] + 1}))::integer as day, s.peak_date
            from used u
            join (select distinct storm_id, peak_date from main.fct_storm_epoch) s using (storm_id)
            join phases p using (norad_id)
        )
        select r.generation, w.home_shell as shell_km, w.day,
               avg(r.rate_m - w.baseline_m) as relative_rate_m, count(*) as satellite_storms
        from wanted w
        join ready r on r.norad_id = w.norad_id and r.epoch_date = w.peak_date + w.day
        group by all
    """).pl()
    con.unregister("used")
    return _round(frame).sort(["shell_km", "generation", "day"])


def descent_sums(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    """Sufficient statistics for the cross-check regression, per generation,
    shell and calendar month.

    Within each satellite-month the rate, ap and F10.7 are each detrended
    against the day (Frisch-Waugh): a commanded descent's steady thrust, the
    satellite's own altitude drift and the slow solar trend all go into the
    trend, and what is left is day-to-day variation. Drag is what makes the
    rate's variation follow ap's.
    """
    return _round(
        con.execute(f"""
        with descent as (
            select r.*, date_trunc('month', r.epoch_date) as month,
                   date_diff('day', date '{PERIOD_START}', r.epoch_date) as t
            from ready r join phases p using (norad_id)
            where r.epoch_date > p.operational_to and r.altitude_shell_km < p.home_shell
        ),
        decaying as (
            select norad_id, month from descent group by all
            having count(*) >= {DESCENT_MIN_DAYS}
               and arg_min(mean_altitude_km, epoch_date) - arg_max(mean_altitude_km, epoch_date)
                   >= {DESCENT_MIN_LOSS_KM}
        ),
        detrended as (
            select d.generation, d.altitude_shell_km as shell_km, d.month,
                {_residual("rate_m")} as y,
                {_residual("ap_mean")} as ap,
                {_residual("f10_7_sfu")} as f
            from descent d join decaying using (norad_id, month)
            where d.ap_mean is not null and d.f10_7_sfu is not null
            window w as (partition by d.norad_id, d.month)
        )
        select generation, shell_km, month, count(*) as n,
               sum(ap * ap) as s_aa, sum(ap * f) as s_af, sum(f * f) as s_ff,
               sum(ap * y) as s_ay, sum(f * y) as s_fy, sum(y * y) as s_yy
        from detrended where y is not null group by all
    """).pl()
    ).sort(["generation", "shell_km", "month"])


def naive_slopes(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    """The comparison the brief warns against: raw daily rate against daily Dst,
    per generation, no controls at all. Kept to show what the controls change."""
    return _round(
        con.execute("""
        select generation, count(*) as satellite_days,
               regr_slope(rate_m, -dst_min_nt / 100.0) as slope_m_per_100nt
        from ready where dst_min_nt is not null group by generation
    """).pl()
    ).sort("generation")


def generations(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    return con.execute("""
        select generation, median_area_to_mass_proxy as area_to_mass, satellites
        from main.dim_generation order by generation
    """).pl()


def phase_days(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    """Satellite-days per generation, phase and year: what figure 1 draws."""
    return (
        con.execute("""
        select r.generation, year(r.epoch_date) as year,
               case when r.epoch_date < p.operational_from then 'raising'
                    when r.epoch_date <= p.operational_to then 'operational'
                    else 'descending' end as phase,
               count(*) as satellite_days
        from ready r join phases p using (norad_id) group by all
    """)
        .pl()
        .sort(["generation", "year", "phase"])
    )


def solar_flux(con: duckdb.DuckDBPyConnection) -> pl.DataFrame:
    return _round(
        con.execute(f"""
        select date_trunc('month', epoch_date) as month, avg(f10_7_sfu) as f10_7_sfu
        from main.fct_space_weather_daily
        where epoch_date between date '{PERIOD_START}' and date '{PERIOD_END}'
        group by all
    """).pl()
    ).sort("month")


def _residual(column: str) -> str:
    """``column`` minus its least-squares line in ``t`` within the window ``w``."""
    slope = f"(covar_pop({column}, t) over w / nullif(var_pop(t) over w, 0))"
    return f"({column} - avg({column}) over w - {slope} * (t - avg(t) over w))"


def _round(frame: pl.DataFrame, significant: int = 10) -> pl.DataFrame:
    """Round every float column to ``significant`` digits."""
    floats = [name for name, dtype in frame.schema.items() if dtype.is_float()]
    return frame.with_columns(pl.col(floats).round_sig_figs(significant))
